{"name": "Valid value for 'roomSize', 'coords', 'patches' and 'instructions' parameter in the request body but getting incorrect output for patches -- @1.2 ", "status": "failed", "statusDetails": {"message": "AssertionError: failed with exception: Actual Output is: {'coords': [0, 0], 'patches': 2}\n", "trace": "  File \"c:\\users\\bansaan\\pycharmprojects\\platformscience\\venv\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"c:\\users\\bansaan\\pycharmprojects\\platformscience\\venv\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\pltscisdetstepsimpl.py\", line 65, in verify_response_body\n    raise AssertionError(\"failed with exception: \" + str(e))\n"}, "steps": [{"name": "Given I Set POST request api endpoint", "status": "passed", "start": 1628184585616, "stop": 1628184585616}, {"name": "When I Set HEADER param request content type as \"application/json.\"", "status": "passed", "start": 1628184585616, "stop": 1628184585617}, {"name": "When Set request Body { \"roomSize\" : [3, 3], \"coords\" : [0,0], \"patches\" : [[0,0]], \"instructions\" : \"NEWSNEWS\" }", "status": "passed", "start": 1628184585618, "stop": 1628184585618}, {"name": "And Send a POST HTTP request", "status": "passed", "start": 1628184585619, "stop": 1628184585659}, {"name": "Then I receive valid HTTP response code 200", "status": "passed", "start": 1628184585659, "stop": 1628184585660}, {"name": "And Response BODY with the right data [0, 0] and 1", "status": "failed", "statusDetails": {"message": "AssertionError: failed with exception: Actual Output is: {'coords': [0, 0], 'patches': 2}\n", "trace": "  File \"c:\\users\\bansaan\\pycharmprojects\\platformscience\\venv\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"c:\\users\\bansaan\\pycharmprojects\\platformscience\\venv\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\pltscisdetstepsimpl.py\", line 65, in verify_response_body\n    raise AssertionError(\"failed with exception: \" + str(e))\n"}, "start": 1628184585660, "stop": 1628184585662}], "parameters": [{"name": "request_body", "value": "{ \"roomSize\" : [3, 3], \"coords\" : [0,0], \"patches\" : [[0,0]], \"instructions\" : \"NEWSNEWS\" }"}, {"name": "coords", "value": "[0, 0]"}, {"name": "patches", "value": "1"}], "start": 1628184585613, "stop": 1628184585663, "uuid": "9186bbae-4bdf-4462-9404-ea8490d62f8b", "historyId": "9890e196e5ee281fe7e41eff58812d61", "fullName": "Test Imaginary Robot for Valid and Invalid Input values for Patches params: Valid value for 'roomSize', 'coords', 'patches' and 'instructions' parameter in the request body but getting incorrect output for patches", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "Test Imaginary Robot for Valid and Invalid Input values for Patches params"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}