{"name": "Valid value for 'roomSize', 'coords', 'patches' and 'instructions' parameter in the request body -- @1.1 ", "status": "broken", "statusDetails": {"message": "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /v1/cleaning-sessions (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x03C15630>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',))\n", "trace": "  File \"c:\\users\\bansaan\\pycharmprojects\\platformscience\\venv\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"c:\\users\\bansaan\\pycharmprojects\\platformscience\\venv\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\pltscisdetstepsimpl.py\", line 51, in send_post_request\n    context.response = http.request(\"POST\", context.request_endpoint, body=encoded_data, headers=context.request_headers)\n  File \"c:\\users\\bansaan\\pycharmprojects\\platformscience\\venv\\lib\\site-packages\\urllib3\\request.py\", line 79, in request\n    method, url, fields=fields, headers=headers, **urlopen_kw\n  File \"c:\\users\\bansaan\\pycharmprojects\\platformscience\\venv\\lib\\site-packages\\urllib3\\request.py\", line 170, in request_encode_body\n    return self.urlopen(method, url, **extra_kw)\n  File \"c:\\users\\bansaan\\pycharmprojects\\platformscience\\venv\\lib\\site-packages\\urllib3\\poolmanager.py\", line 375, in urlopen\n    response = conn.urlopen(method, u.request_uri, **kw)\n  File \"c:\\users\\bansaan\\pycharmprojects\\platformscience\\venv\\lib\\site-packages\\urllib3\\connectionpool.py\", line 796, in urlopen\n    **response_kw\n  File \"c:\\users\\bansaan\\pycharmprojects\\platformscience\\venv\\lib\\site-packages\\urllib3\\connectionpool.py\", line 796, in urlopen\n    **response_kw\n  File \"c:\\users\\bansaan\\pycharmprojects\\platformscience\\venv\\lib\\site-packages\\urllib3\\connectionpool.py\", line 796, in urlopen\n    **response_kw\n  File \"c:\\users\\bansaan\\pycharmprojects\\platformscience\\venv\\lib\\site-packages\\urllib3\\connectionpool.py\", line 756, in urlopen\n    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]\n  File \"c:\\users\\bansaan\\pycharmprojects\\platformscience\\venv\\lib\\site-packages\\urllib3\\util\\retry.py\", line 574, in increment\n    raise MaxRetryError(_pool, url, error or ResponseError(cause))\n"}, "steps": [{"name": "Given I Set POST request api endpoint", "status": "passed", "start": 1628197290985, "stop": 1628197290986}, {"name": "When I Set HEADER param request content type as \"application/json.\"", "status": "passed", "start": 1628197290986, "stop": 1628197290986}, {"name": "When Set request Body { \"roomSize\" : [5, 5], \"coords\" : [1, 2], \"patches\" : [ [1, 0], [2, 2], [2, 3] ], \"instructions\" : \"NNESEESWNWW\" }", "status": "passed", "start": 1628197290987, "stop": 1628197290987}, {"name": "And Send a POST HTTP request", "status": "broken", "statusDetails": {"message": "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /v1/cleaning-sessions (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x03C15630>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',))\n", "trace": "  File \"c:\\users\\bansaan\\pycharmprojects\\platformscience\\venv\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"c:\\users\\bansaan\\pycharmprojects\\platformscience\\venv\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\pltscisdetstepsimpl.py\", line 51, in send_post_request\n    context.response = http.request(\"POST\", context.request_endpoint, body=encoded_data, headers=context.request_headers)\n  File \"c:\\users\\bansaan\\pycharmprojects\\platformscience\\venv\\lib\\site-packages\\urllib3\\request.py\", line 79, in request\n    method, url, fields=fields, headers=headers, **urlopen_kw\n  File \"c:\\users\\bansaan\\pycharmprojects\\platformscience\\venv\\lib\\site-packages\\urllib3\\request.py\", line 170, in request_encode_body\n    return self.urlopen(method, url, **extra_kw)\n  File \"c:\\users\\bansaan\\pycharmprojects\\platformscience\\venv\\lib\\site-packages\\urllib3\\poolmanager.py\", line 375, in urlopen\n    response = conn.urlopen(method, u.request_uri, **kw)\n  File \"c:\\users\\bansaan\\pycharmprojects\\platformscience\\venv\\lib\\site-packages\\urllib3\\connectionpool.py\", line 796, in urlopen\n    **response_kw\n  File \"c:\\users\\bansaan\\pycharmprojects\\platformscience\\venv\\lib\\site-packages\\urllib3\\connectionpool.py\", line 796, in urlopen\n    **response_kw\n  File \"c:\\users\\bansaan\\pycharmprojects\\platformscience\\venv\\lib\\site-packages\\urllib3\\connectionpool.py\", line 796, in urlopen\n    **response_kw\n  File \"c:\\users\\bansaan\\pycharmprojects\\platformscience\\venv\\lib\\site-packages\\urllib3\\connectionpool.py\", line 756, in urlopen\n    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]\n  File \"c:\\users\\bansaan\\pycharmprojects\\platformscience\\venv\\lib\\site-packages\\urllib3\\util\\retry.py\", line 574, in increment\n    raise MaxRetryError(_pool, url, error or ResponseError(cause))\n"}, "start": 1628197290988, "stop": 1628197307087}, {"name": "Then I receive valid HTTP response code 200", "status": "skipped", "start": 1628197307090, "stop": 1628197307090}, {"name": "And Response BODY with the right data [1, 3] and 1", "status": "skipped", "start": 1628197307090, "stop": 1628197307090}], "parameters": [{"name": "request_body", "value": "{ \"roomSize\" : [5, 5], \"coords\" : [1, 2], \"patches\" : [ [1, 0], [2, 2], [2, 3] ], \"instructions\" : \"NNESEESWNWW\" }"}, {"name": "coords", "value": "[1, 3]"}, {"name": "patches", "value": "1"}], "start": 1628197290983, "stop": 1628197307090, "uuid": "b1b74e31-3662-4bed-9cf3-43c9b540322e", "historyId": "65e43992a30fb1399b3f253324d4704a", "fullName": "Test Imaginary Robot for Valid and Invalid Input values for roomSize params: Valid value for 'roomSize', 'coords', 'patches' and 'instructions' parameter in the request body", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "Test Imaginary Robot for Valid and Invalid Input values for roomSize params"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}