{"name": "Valid value for 'roomSize', 'coords', 'patches' and 'instructions' parameter in the request body but getting incorrect output for patches -- @1.3 ", "status": "failed", "statusDetails": {"message": "AssertionError: failed with exception: Actual Output is: {'coords': [1, 1], 'patches': 3}\n", "trace": "  File \"c:\\users\\bansaan\\pycharmprojects\\platformscience\\venv\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"c:\\users\\bansaan\\pycharmprojects\\platformscience\\venv\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\pltscisdetstepsimpl.py\", line 65, in verify_response_body\n    raise AssertionError(\"failed with exception: \" + str(e))\n"}, "steps": [{"name": "Given I Set POST request api endpoint", "status": "passed", "start": 1628184045178, "stop": 1628184045179}, {"name": "When I Set HEADER param request content type as \"application/json.\"", "status": "passed", "start": 1628184045179, "stop": 1628184045180}, {"name": "When Set request Body { \"roomSize\" : [5, 5], \"coords\" : [1, 1], \"patches\" : [[2, 2]], \"instructions\" : \"NESW\" }", "status": "passed", "start": 1628184045180, "stop": 1628184045182}, {"name": "And Send a POST HTTP request", "status": "passed", "start": 1628184045182, "stop": 1628184045193}, {"name": "Then I receive valid HTTP response code 200", "status": "passed", "start": 1628184045193, "stop": 1628184045194}, {"name": "And Response BODY with the right data [1, 1] and 1", "status": "failed", "statusDetails": {"message": "AssertionError: failed with exception: Actual Output is: {'coords': [1, 1], 'patches': 3}\n", "trace": "  File \"c:\\users\\bansaan\\pycharmprojects\\platformscience\\venv\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"c:\\users\\bansaan\\pycharmprojects\\platformscience\\venv\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\pltscisdetstepsimpl.py\", line 65, in verify_response_body\n    raise AssertionError(\"failed with exception: \" + str(e))\n"}, "start": 1628184045194, "stop": 1628184045196}], "parameters": [{"name": "request_body", "value": "{ \"roomSize\" : [5, 5], \"coords\" : [1, 1], \"patches\" : [[2, 2]], \"instructions\" : \"NESW\" }"}, {"name": "coords", "value": "[1, 1]"}, {"name": "patches", "value": "1"}], "start": 1628184045176, "stop": 1628184045197, "uuid": "7e8a43a6-14eb-431b-929a-59bcc7833f9e", "historyId": "d92d6bb5a8ef11bb9ab23f934ec4bf15", "fullName": "Test Imaginary Robot for Valid and Invalid Input values for Patches params: Valid value for 'roomSize', 'coords', 'patches' and 'instructions' parameter in the request body but getting incorrect output for patches", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "Test Imaginary Robot for Valid and Invalid Input values for Patches params"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}